# -*- coding: utf-8 -*-
"""Monthly BO - Dont delete

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1th8AgIM2hktlXNjZ0-hBap0vbz0DgrFM
"""

!pip install yfinance

from curl_cffi import requests
session = requests.Session(impersonate="chrome")
import yfinance as yf

# List of ticker symbols
tickers = ["RELIANCE.NS", "TATAMOTORS.NS", "INFY.NS"]

# Create a dictionary to store the dataframes
stock_data = {}

# Loop through each ticker and download the data
for ticker in tickers:
    data = yf.download(
        tickers=ticker,
        start="2003-01-01",
        interval="1mo",session=session
    )
    # Store the data in the dictionary using the ticker as the key
    stock_data[ticker] = data
    print(f"Downloaded monthly data for {ticker}!")

# Example: Access data for Reliance Industries
print(stock_data["RELIANCE.NS"].head())

import yfinance as yf
import pandas as pd
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor
import time
import random
import os
from tqdm import tqdm
import shutil

def build_marketcap_csv(save_path="/content/drive/MyDrive/stocks_market_cap.csv",
                        batch_size=50, delay=1):
    """
    Downloads all NSE tickers and fetches Yahoo Finance data.
    Overwrites the file used by downstream scripts.

    Columns: ['Symbols', 'marketcap', 'last_price', 'pe_ratio', 'pb_ratio', 'sector', 'currency']
    """
    # Step 1: Download all NSE symbols
    url = "https://archives.nseindia.com/content/equities/EQUITY_L.csv"
    print("📥 Downloading list of NSE symbols...")
    df_all = pd.read_csv(url)
    tickers = df_all["SYMBOL"].astype(str) + ".NS"

    results = []

    # Step 2: Batch fetch with rate control
    for i in tqdm(range(0, len(tickers), batch_size)):
        batch = tickers[i:i+batch_size]
        for t in batch:
            try:
                stock = yf.Ticker(t)
                info = stock.info

                market_cap = info.get("marketCap")
                last_price = info.get("currentPrice") or info.get("lastPrice")
                pe_ratio = info.get("trailingPE")
                pb_ratio = info.get("priceToBook")
                sector = info.get("sector")
                currency = info.get("currency")

                if market_cap:
                    market_cap_cr = round(market_cap / 1e7, 2)  # Convert to ₹ crores
                else:
                    market_cap_cr = None

                results.append({
                    "Symbols": t,  # match downstream name
                    "marketcap": market_cap_cr,
                    "last_price": last_price,
                    "pe_ratio": pe_ratio,
                    "pb_ratio": pb_ratio,
                    "sector": sector,
                    "currency": currency
                })

            except Exception:
                continue
        time.sleep(delay)

    # Step 3: Combine and save
    df_result = pd.DataFrame(results).sort_values("marketcap", ascending=False)

    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    df_result.to_csv(save_path, index=False, encoding="utf-8-sig")

    print(f"\n✅ Saved {len(df_result)} tickers to {save_path}")
    return df_result

from google.colab import drive
drive.mount('/content/drive')

# # 2️⃣ Build the live list
# df = build_marketcap_csv()

tickers_df = pd.read_csv('/content/drive/MyDrive/stocks_market_cap.csv')
tickers = tickers_df['Symbols'].to_list()

# Map market cap data for each ticker
market_cap_map = tickers_df.set_index('Symbols')['marketcap'].to_dict()


def download_with_retries(ticker, start, interval, max_retries=3, pause_seconds=10):
    attempt = 0
    while attempt < max_retries:
        try:
            data = yf.download(ticker, start=start, interval=interval, multi_level_index=False)
            if data.empty:
                raise ValueError("Empty data returned")
            return data
        except Exception as e:
            attempt += 1
            print(f"Attempt {attempt} failed for {ticker}: {e}")
            time.sleep(pause_seconds * attempt)  # Exponential backoff
    print(f"All retries failed for {ticker}")
    return pd.DataFrame()  # Return empty DataFrame on total failure


# Function to process a single stock
def process_stock(ticker):
    try:
        data_dir = "stock_data"
        os.makedirs(data_dir, exist_ok=True)
        file_path = os.path.join(data_dir, f"{ticker}.csv")

        if os.path.exists(file_path):
            # Load previously saved data
            data = pd.read_csv(file_path, parse_dates=['Date'])
        else:
            # Fetch data and save it
            data = download_with_retries(ticker, start="2003-01-01", interval="1mo")
            if data.empty:
                print(f"No data for {ticker}")
                return pd.DataFrame()
            data = data.reset_index()
            data = data[['Date', 'Open', 'High', 'Low', 'Close']]
            data.to_csv(file_path, index=False)

        # Create a new column for month
        data['Month'] = data['Date'].dt.to_period('M')

        # Initialize 'Highest High', 'Highest High Month', 'Highest Close', and 'Highest Close Month'
        data['Highest High'] = data['High'].cummax()
        data['Highest High Month'] = data.apply(lambda row: data[data['High'] == row['Highest High']]['Month'].min(), axis=1)

        data['Highest Close'] = data['Close'].cummax()
        data['Highest Close Month'] = data.apply(lambda row: data[data['Close'] == row['Highest Close']]['Month'].min(), axis=1)

        # Calculate 2nd highest high and the month of the 2nd highest high
        def calculate_2nd_highest(row, data):
            current_idx = data.index.get_loc(row.name)
            if current_idx > 0:
                previous_data = data.loc[:row.name]
                top_two_highs = previous_data['High'].nlargest(2)
                if len(top_two_highs) > 1:
                    second_highest = top_two_highs.iloc[-1]
                    second_highest_month = previous_data.loc[previous_data['High'] == second_highest, 'Month'].min()
                    return second_highest, second_highest_month
                else:
                    return None, None
            else:
                return None, None

        data['2nd Highest High'], data['2nd Highest High Month'] = zip(*data.apply(lambda row: calculate_2nd_highest(row, data), axis=1))

        data['Highest High Highest Close'] = data.apply(
            lambda row: "Yes" if row['Month'] == row['Highest High Month'] and row['Month'] == row['Highest Close Month'] and (row['2nd Highest High'] is not None and row['Close'] >= row['2nd Highest High']) else "", axis=1
        )

        # Calculate the second-highest close and its month
        def calculate_2nd_highest_close(row, data):
            current_idx = data.index.get_loc(row.name)
            if current_idx > 0:
                previous_data = data.loc[:row.name]
                top_two_closes = previous_data['Close'].nlargest(2)
                if len(top_two_closes) > 1:
                    second_highest_close = top_two_closes.iloc[-1]
                    second_highest_close_month = previous_data.loc[previous_data['Close'] == second_highest_close, 'Month'].min()
                    return second_highest_close, second_highest_close_month
                else:
                    return None, None
            else:
                return None, None

        data['2nd Highest Close'], data['2nd Highest Close Month'] = zip(
            *data.apply(lambda row: calculate_2nd_highest_close(row, data), axis=1)
        )

        # def calculate_duration(row):
        #     if row['Highest High Highest Close'] == "Yes" and row['2nd Highest High Month'] is not None:
        #         current_month = row['Month'].start_time
        #         second_highest_month = row['2nd Highest High Month'].start_time
        #         duration = (current_month.year - second_highest_month.year) * 12 + current_month.month - second_highest_month.month
        #         return duration
        #     else:
        #         return ""

        def calculate_duration(row):
            if row['Highest High Highest Close'] == "Yes":
                # Get the date of the highest high and highest close month
                highest_high_month = row['Highest High Month'].start_time
                highest_close_month = row['Highest Close Month'].start_time

                # Determine the second-highest (either close or high)
                second_highest_value = None
                second_highest_month = None

                # Check if the second-highest high is available
                if row['2nd Highest High'] is not None:
                    second_highest_value = row['2nd Highest High']
                    second_highest_month = row['2nd Highest High Month'].start_time

                # Check if the second-highest close is available
                elif row['2nd Highest Close'] is not None:
                    second_highest_value = row['2nd Highest Close']
                    second_highest_month = row['2nd Highest Close Month'].start_time

                # Calculate duration between highest and second-highest (whether high or close)
                if second_highest_value is not None and second_highest_month:
                    duration = (highest_close_month.year - second_highest_month.year) * 12 + highest_close_month.month - second_highest_month.month
                    return duration
                else:
                    return ""  # No valid second-highest value to compare

            return ""


        data['Duration'] = data.apply(calculate_duration, axis=1)

        # Calculate today's 20-Month EMA based on the last 20 months of closing prices
        # EMA calculation based on the most recent 20 months of data for each row.
        today_ema = data['Close'].iloc[-20:].ewm(span=20, adjust=False).mean().iloc[-1]

        data['20-Month EMA'] = today_ema

        # Add the latest price (today's closing price)
        latest_price = yf.download(ticker, period="1d", interval="1d",multi_level_index=False)['Close'].iloc[-1]
        data['Latest Price'] = latest_price

        # Add % Difference from Smoothed 20-Month EMA
        data['% Diff from 20-Month EMA'] = ((latest_price - today_ema) / today_ema) * 100

        # Add % Difference between Latest Price and 2nd Highest High
        data['% Diff from 2nd Highest High'] = ((latest_price - data['2nd Highest High']) / data['2nd Highest High']) * 100

        # Add Market Cap column
        data['Market Cap'] = market_cap_map.get(ticker, None)

        # Add a column for the ticker to identify which stock the data belongs to
        data['Ticker'] = ticker

        return data

    except Exception as e:
        print(f"Error processing {ticker}: {e}")
        return pd.DataFrame()

# Function to apply a timeout on stock processing
def process_stock_with_timeout(ticker,timeout=60):
    with ThreadPoolExecutor(max_workers=1) as executor:
        future = executor.submit(process_stock, ticker)
        try:
            result = future.result(timeout=timeout)
        except Exception as e:
            print(f"Timeout or error for {ticker}: {e}")
            return pd.DataFrame()  # Return empty DataFrame in case of timeout/error
    return result

def push_to_drive(local_file, drive_folder="/content/drive/MyDrive/GodsGrace"):
    """
    Copies the given output CSV file to a target folder in Google Drive.
    Assumes Drive is already mounted.
    """
    # Ensure folder exists
    os.makedirs(drive_folder, exist_ok=True)

    # Define destination path
    dest_path = os.path.join(drive_folder, os.path.basename(local_file))

    # Copy file to Drive
    shutil.copy(local_file, dest_path)

    print(f"✅ File successfully copied to Google Drive: {dest_path}")
    return dest_path

# Batch processing
def batch_process_stocks(tickers, batch_size=100):
    # Create a unique filename with timestamp for every run
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = f"Stocks_Analysis_{timestamp}.csv"

    num_batches = len(tickers) // batch_size + (1 if len(tickers) % batch_size != 0 else 0)

    for batch_num in range(num_batches):
        start_idx = batch_num * batch_size
        end_idx = min(start_idx + batch_size, len(tickers))
        tickers_batch = tickers[start_idx:end_idx]

        print(f"Processing batch {batch_num+1}/{num_batches} (Tickers {start_idx+1} to {end_idx})...")

        batch_data = []  # Temporary storage for the current batch

        for ticker in tickers_batch:
            print(f"Processing {ticker}...")
            time.sleep(random.uniform(1, 3))
            stock_data = process_stock_with_timeout(ticker)
            if not stock_data.empty:
                batch_data.append(stock_data)

        if batch_data:
            # Combine the current batch data
            batch_data_df = pd.concat(batch_data, ignore_index=True)

            # Filter rows meeting the condition
            filtered_data = batch_data_df[(batch_data_df['Highest High Highest Close'] == 'Yes')]

            # Append the filtered data to the output CSV file
            if not filtered_data.empty:
                with open(output_file, mode='a', newline='', encoding='utf-8') as f:
                    filtered_data.to_csv(f, index=False, header=f.tell() == 0)  # Add header only if the file is empty

            print(f"Batch {batch_num+1} appended to {output_file}.")

    print(f"All stocks processed and saved to {output_file}.")
    push_to_drive(output_file)


# Run batch processing
batch_process_stocks(tickers)

import matplotlib.pyplot as plt
import seaborn as sns

# Create a DataFrame from the filtered_month_counts Series for easier plotting
plot_df = filtered_month_counts.reset_index()
plot_df.columns = ['Month', 'Count']

# Ensure 'Month' is in a sortable format (e.g., datetime objects)
# The index of filtered_month_counts is already converted to datetime in the previous step
# If filtered_month_counts was not passed from the previous step, this step could be needed:
# plot_df['Month'] = pd.to_datetime(plot_df['Month'])

# Sort the DataFrame by month for chronological order on the plot
plot_df = plot_df.sort_values(by='Month')

plt.figure(figsize=(14, 7))
sns.barplot(x='Month', y='Count', data=plot_df, palette='viridis')
plt.title('Monthly Value Counts (2024-01 to 2025-12)')
plt.xlabel('Month')
plt.ylabel('Number of Occurrences')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

import pandas as pd

file_path = '/content/drive/MyDrive/GodsGrace/Stocks_Analysis_20251231_142511.csv'
df = pd.read_csv(file_path)

# Perform value counts on the 'Month' column
month_value_counts = df['Month'].value_counts()

# Convert the index of month_value_counts to datetime objects for filtering
month_value_counts_converted = pd.to_datetime(month_value_counts.index)

# Define the start and end of the desired range
start_date = pd.to_datetime('2024-01')
end_date = pd.to_datetime('2025-12')

# Filter the Series based on the date range
filtered_month_counts = month_value_counts[
    (month_value_counts_converted >= start_date) &
    (month_value_counts_converted <= end_date)
]

display(filtered_month_counts)

import pandas as pd

file_path = '/content/drive/MyDrive/GodsGrace/Stocks_Analysis_20251231_142511.csv'
df = pd.read_csv(file_path)

# Perform value counts on the 'Month' column
month_value_counts = df['Month'].value_counts()
display(month_value_counts)

!ls /content/drive/MyDrive/stock_data | wc -l

!mv /content/Stocks_Analysis_20251001_112403.csv /content/drive/MyDrive/

!mv /content/stocks_market_cap_2000.csv /content/drive/MyDrive/

